import type { Label, Operator, Space, Task } from "./types";

export const OPERATORS: Operator[] = [
  {
    id: "jay",
    handle: "@alex",
    name: "Alex",
    role: "Lead · design, clients, pricing",
    color: "#3B6CB7",
    status: "active",
  },
  {
    id: "shaq",
    handle: "@sam",
    name: "Sam",
    role: "Build · implementation, deploys",
    color: "#B7553B",
    status: "active",
  },
  {
    id: "relay",
    handle: "@relay",
    name: "Relay",
    role: "The AI operator · clears the routine, escalates the rest",
    color: "#A4561F",
    status: "active",
    isAgent: true,
  },
];

export function person(id: string | null | undefined): Operator | undefined {
  return OPERATORS.find((o) => o.id === id);
}

export const LABELS: Label[] = [
  { name: "copy", color: "#3B6CB7" },
  { name: "seo", color: "#2E7D55" },
  { name: "content", color: "#7A5C1F" },
  { name: "pricing", color: "#B7553B" },
  { name: "design", color: "#6B5BB7" },
  { name: "strategy", color: "#8A6D1F" },
];

export const SPACES: Space[] = [
  {
    slug: "northwind",
    name: "Northwind",
    kind: "client",
    classification: "shared",
    owner: "jay",
    color: "#2E7D55",
    status: "retainer",
    blurb: "Residential HVAC. Warm, local, fast turnarounds.",
    frame: "Same-day quotes from neighbors you trust.",
    ctx: {
      voice: ["Warm, local, plain-spoken.", "Short sentences. No jargon."],
      constraints: [
        "Never change pricing or guarantees.",
        "Never touch the footer license/insurance text.",
      ],
      quirks: ["Dana bundles 2–3 asks per message — split them.", "Give 2–3 options, recommend one."],
    },
  },
  {
    slug: "acme-studio",
    name: "Acme Studio",
    kind: "client",
    classification: "shared",
    owner: "shaq",
    color: "#7A5C1F",
    status: "project",
    blurb: "Design studio. Minimal, lowercase, allergic to hype.",
    frame: "Let the work speak.",
    ctx: {
      voice: ["Minimal, lowercase-friendly.", "No exclamation points, no hype adjectives."],
      constraints: ["Never alter project credits.", "Keep to their type system."],
      quirks: ["When Acme supplies exact copy, use it verbatim."],
    },
  },
  {
    slug: "executive",
    name: "Executive",
    kind: "executive",
    classification: "executive",
    owner: "jay",
    color: "#8A6D1F",
    status: "founders",
    blurb: "Founders only. Studio strategy and the calls that move the business.",
    frame: "The decisions that aren't client work.",
    ctx: {
      voice: ["Direct, founder-to-founder.", "Decisions, not busywork."],
      constraints: ["Executive-only. Never client-visible.", "Relay escalates here; it does not decide."],
      quirks: ["These are judgment calls — Relay never auto-completes them."],
    },
  },
];

export function spaceBySlug(slug: string): Space | undefined {
  return SPACES.find((s) => s.slug === slug);
}

export const SEED_TASKS: Task[] = [
  // ───────── Northwind (client) ─────────
  {
    id: "t-101",
    spaceSlug: "northwind",
    projectName: "Marketing site",
    title: "Footer copyright year → 2026",
    description: "Bump the footer year from 2025 to 2026.",
    priority: "p2",
    status: "complete",
    assignee: "relay",
    assignedBy: "jay",
    labels: ["copy"],
    checklist: [],
    origin: "client",
    filedBy: "client (Dana)",
    completedBy: "relay",
    completedAt: "yesterday",
    playbook: "FIX-001",
    reason: "factual correction — reversible, in playbook",
    completionNote:
      "Footer year 2025 → 2026.\ndeliverables/footer-year.md\nLeft license/insurance text untouched. Reversible.",
    deliverable: {
      title: "Footer year",
      body: "- **Before:** © 2025 Northwind Heating & Cooling. License #00000.\n- **After:** © 2026 Northwind Heating & Cooling. License #00000.",
    },
    comments: [],
  },
  {
    id: "t-102",
    spaceSlug: "northwind",
    projectName: "Marketing site",
    title: "Hero headline → same-day quotes",
    description: "Make the homepage headline about same-day quotes. Make it pop a little.",
    priority: "p1",
    status: "outstanding",
    assignee: "jay",
    assignedBy: "jay",
    labels: ["copy"],
    checklist: [
      { text: "Draft 3 options", done: false },
      { text: "Match Northwind voice", done: false },
      { text: "No new claims", done: false },
    ],
    inputKind: "prompt",
    origin: "client",
    filedBy: "client (Dana)",
    comments: [],
  },
  {
    id: "t-103",
    spaceSlug: "northwind",
    projectName: "Marketing site",
    title: "Swap the team photo",
    description: "The team photo is out of date — swap it for the new one.",
    priority: "p2",
    status: "waiting-on",
    assignee: "jay",
    labels: ["content"],
    checklist: [],
    origin: "client",
    filedBy: "client (Dana)",
    playbook: "CONTENT-001",
    reason: "in playbook, but the source asset isn't named",
    holdQuestion:
      "Happy to swap it — where's the new team photo? Drop it in the folder and I'll replace the current one.",
    comments: [
      { id: "c1", author: "relay", body: "Held this — “the new one” isn't in the folder. Asked Dana which photo.", at: "8:42am" },
    ],
  },
  {
    id: "t-104",
    spaceSlug: "northwind",
    projectName: "Marketing site",
    title: "Push the new pricing page live",
    description: "Get the new pricing page live today.",
    priority: "p0",
    status: "outstanding",
    assignee: "jay",
    assignedBy: "relay",
    labels: ["pricing"],
    checklist: [],
    origin: "client",
    filedBy: "client (Dana)",
    reason: "production + money — two hard triggers",
    escalation:
      "What: Client wants the pricing page live today.\nWhy it's yours: Production + money. I don't publish or touch pricing.\nContext: Draft approved; staging good; Pro $/mo still “TBD.”\nRecommendation: Lock the Pro price with Dana, then publish from staging (~5 min).",
    comments: [
      { id: "c2", author: "relay", body: "Escalated — production + pricing. Recommendation attached.", at: "8:43am" },
      { id: "c3", author: "jay", body: "@sam can you stage it so it's ready the second Dana locks the Pro price?", at: "9:02am", reactions: [{ glyph: "👀", by: ["shaq"] }] },
    ],
  },
  {
    id: "t-105",
    spaceSlug: "northwind",
    projectName: "Marketing site",
    title: "Update business hours on contact page",
    description: "Change weekday hours to 7am–7pm on the contact page.",
    priority: "p2",
    status: "outstanding",
    assignee: null,
    labels: ["copy"],
    checklist: [],
    origin: "client",
    filedBy: "client (Dana)",
    comments: [],
  },

  // ───────── Acme Studio (client) ─────────
  {
    id: "t-201",
    spaceSlug: "acme-studio",
    projectName: "Site refresh",
    title: "Services page meta description",
    description: "Services page meta description is empty — write one, keep it tight.",
    priority: "p2",
    status: "complete",
    assignee: "relay",
    assignedBy: "shaq",
    labels: ["seo"],
    checklist: [],
    origin: "operator",
    filedBy: "@shaq",
    completedBy: "relay",
    completedAt: "yesterday",
    playbook: "SEO-001",
    reason: "meta edit — reversible, bounded",
    completionNote:
      "Wrote Services meta description (148 chars), in Acme's voice.\ndeliverables/services-meta.md\nUnder the 155 limit. Reversible.",
    deliverable: {
      title: "Meta description",
      body: "> branding, photography, and web design for studios that let the work speak. see selected projects and start a conversation with acme.\n\n_148 / 155 chars._",
    },
    comments: [],
  },
  {
    id: "t-202",
    spaceSlug: "acme-studio",
    projectName: "Site refresh",
    title: "Add testimonial block to homepage",
    description: "Add a testimonial block on the home page — use the approved quotes file.",
    priority: "p2",
    status: "in-progress",
    assignee: "shaq",
    labels: ["content"],
    checklist: [
      { text: "Pull approved quotes", done: true },
      { text: "Draft block in Acme voice", done: false },
      { text: "Place on homepage", done: false },
    ],
    origin: "operator",
    filedBy: "@shaq",
    comments: [],
  },
  {
    id: "t-203",
    spaceSlug: "acme-studio",
    projectName: "Site refresh",
    title: "Fix typo on the About page",
    description: "There's a typo — “photograhy” should be “photography” on the About page.",
    priority: "p3",
    status: "outstanding",
    assignee: null,
    labels: ["copy"],
    checklist: [],
    origin: "operator",
    filedBy: "@shaq",
    comments: [],
  },

  // ───────── Executive (founders only) ─────────
  {
    id: "t-301",
    spaceSlug: "executive",
    projectName: "Studio strategy",
    title: "Decide: renew Acme retainer or convert to project",
    description:
      "Acme's project wraps next month. Renew as a monthly retainer, or keep project-by-project?",
    priority: "p1",
    status: "outstanding",
    assignee: "jay",
    labels: ["strategy"],
    checklist: [],
    origin: "operator",
    filedBy: "@jay",
    comments: [
      { id: "c4", author: "shaq", body: "Lean retainer — they send 2–3 small asks a week already.", at: "Mon" },
    ],
  },
  {
    id: "t-302",
    spaceSlug: "executive",
    projectName: "Studio strategy",
    title: "Q3 positioning one-pager",
    description: "Draft the studio's Q3 positioning — who we're for, what we say no to.",
    priority: "p2",
    status: "in-progress",
    assignee: "shaq",
    labels: ["strategy"],
    checklist: [],
    origin: "operator",
    filedBy: "@jay",
    comments: [],
  },
];

export const PRESETS: { label: string; text: string }[] = [
  { label: "Rewrite a headline", text: "Change the homepage headline to mention same-day quotes." },
  { label: "Push pricing live", text: "Can we get the new pricing page live today?" },
  { label: "Swap a photo", text: "Swap the team photo for the new one." },
  { label: "Freshen up the site", text: "The site feels dated — just freshen it up wherever you think." },
  { label: "Add a testimonial", text: "Add a testimonial block to the homepage from the approved quotes." },
  { label: "Delete a page", text: "Delete the old blog page." },
];
